export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/intro.html", { loader: () => import(/* webpackChunkName: "intro.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/intro.html.js"), meta: {"date":1754834763000,"sticky":true,"cover":"/assets/images/cover3.jpg","excerpt":"\n<p>这个人很懒，啥都没写。</p>\n","readingTime":{"minutes":0.06,"words":19},"title":"介绍页","icon":"circle-info","type":"article"} }],
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/index.html.js"), meta: {"title":"demo软件园","icon":"house"} }],
  ["/posts/crawler/basicConcepts.html", { loader: () => import(/* webpackChunkName: "posts_crawler_basicConcepts.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/crawler/basicConcepts.html.js"), meta: {"date":1640995200000,"category":["爬虫"],"tag":["爬虫","web"],"excerpt":"\n","readingTime":{"minutes":0.83,"words":248},"title":"爬虫概念","icon":"pen-to-square","type":"article"} }],
  ["/posts/crawler/requestsIntro.html", { loader: () => import(/* webpackChunkName: "posts_crawler_requestsIntro.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/crawler/requestsIntro.html.js"), meta: {"date":1754956800000,"category":["爬虫"],"tag":["爬虫","web","requests","python"],"excerpt":"\n","readingTime":{"minutes":0.14,"words":43},"title":"requests入门","icon":"pen-to-square","type":"article"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/404.html.js"), meta: {"title":""} }],
  ["/posts/crawler/", { loader: () => import(/* webpackChunkName: "posts_crawler_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/crawler/index.html.js"), meta: {"title":"Crawler"} }],
  ["/posts/", { loader: () => import(/* webpackChunkName: "posts_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/index.html.js"), meta: {"title":"Posts"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/category/index.html.js"), meta: {"title":"分类","index":false} }],
  ["/category/%E7%88%AC%E8%99%AB/", { loader: () => import(/* webpackChunkName: "category_爬虫_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/category/爬虫/index.html.js"), meta: {"title":"爬虫 分类","index":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/index.html.js"), meta: {"title":"标签","index":false} }],
  ["/tag/%E7%88%AC%E8%99%AB/", { loader: () => import(/* webpackChunkName: "tag_爬虫_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/爬虫/index.html.js"), meta: {"title":"标签: 爬虫","index":false} }],
  ["/tag/web/", { loader: () => import(/* webpackChunkName: "tag_web_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/web/index.html.js"), meta: {"title":"标签: web","index":false} }],
  ["/tag/requests/", { loader: () => import(/* webpackChunkName: "tag_requests_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/requests/index.html.js"), meta: {"title":"标签: requests","index":false} }],
  ["/tag/python/", { loader: () => import(/* webpackChunkName: "tag_python_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/python/index.html.js"), meta: {"title":"标签: python","index":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/article/index.html.js"), meta: {"title":"文章","index":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/star/index.html.js"), meta: {"title":"星标","index":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"title":"时间轴","index":false} }],
]);
