export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/intro.html", { loader: () => import(/* webpackChunkName: "intro.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/intro.html.js"), meta: {"cover":"/assets/images/cover3.jpg","excerpt":"\n<p>将你的个人介绍和档案放置在此处。</p>\n","readingTime":{"minutes":0.08,"words":23},"title":"介绍页","icon":"circle-info","type":"article"} }],
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/index.html.js"), meta: {"title":"博客主页","icon":"house"} }],
  ["/demo/disable.html", { loader: () => import(/* webpackChunkName: "demo_disable.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/demo/disable.html.js"), meta: {"category":["使用指南"],"tag":["禁用"],"excerpt":"<p>你可以通过设置页面的 Frontmatter，在页面禁用功能与布局。</p>\n","readingTime":{"minutes":0.43,"words":128},"title":"布局与功能禁用","icon":"gears","order":4,"type":"article"} }],
  ["/demo/encrypt.html", { loader: () => import(/* webpackChunkName: "demo_encrypt.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/demo/encrypt.html.js"), meta: {"category":["使用指南"],"tag":["加密"],"isEncrypted":true,"readingTime":{"minutes":0.51,"words":154},"title":"密码加密的文章","icon":"lock","type":"article"} }],
  ["/demo/layout.html", { loader: () => import(/* webpackChunkName: "demo_layout.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/demo/layout.html.js"), meta: {"category":["指南"],"tag":["布局"],"excerpt":"<p>布局包括:</p>\n<ul>\n<li><a href=\"https://theme-hope.vuejs.press/zh/guide/layout/navbar.html\" target=\"_blank\" rel=\"noopener noreferrer\">导航栏</a></li>\n<li><a href=\"https://theme-hope.vuejs.press/zh/guide/layout/sidebar.html\" target=\"_blank\" rel=\"noopener noreferrer\">侧边栏</a></li>\n<li><a href=\"https://theme-hope.vuejs.press/zh/guide/layout/footer.html\" target=\"_blank\" rel=\"noopener noreferrer\">页脚</a></li>\n</ul>","readingTime":{"minutes":0.53,"words":159},"title":"布局","icon":"object-group","order":2,"type":"article"} }],
  ["/demo/markdown.html", { loader: () => import(/* webpackChunkName: "demo_markdown.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/demo/markdown.html.js"), meta: {"category":["使用指南"],"tag":["Markdown"],"excerpt":"<p>VuePress 主要从 Markdown 文件生成页面。因此，你可以使用它轻松生成文档或博客站点。</p>\n<p>你需要创建并编写 Markdown，以便 VuePress 可以根据文件结构将它们转换为不同的页面。</p>\n","readingTime":{"minutes":3.13,"words":938},"title":"Markdown 展示","icon":"fa6-brands:markdown","order":2,"type":"article"} }],
  ["/demo/page.html", { loader: () => import(/* webpackChunkName: "demo_page.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/demo/page.html.js"), meta: {"author":"Ms.Hope","date":1577836800000,"category":["使用指南"],"tag":["页面配置","使用指南"],"sticky":true,"cover":"/assets/images/cover1.jpg","excerpt":"<p><code>more</code> 注释之前的内容被视为文章摘要。</p>\n","readingTime":{"minutes":1.76,"words":529},"title":"页面配置","icon":"file","order":3,"type":"article"} }],
  ["/demo/", { loader: () => import(/* webpackChunkName: "demo_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/demo/index.html.js"), meta: {"category":["使用指南"],"readingTime":{"minutes":0.07,"words":22},"title":"主要功能与配置演示","icon":"laptop-code","type":"article"} }],
  ["/posts/cherry.html", { loader: () => import(/* webpackChunkName: "posts_cherry.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/cherry.html.js"), meta: {"date":1641686400000,"category":["樱桃"],"tag":["红","小","圆"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.11,"words":33},"title":"樱桃","icon":"pen-to-square","type":"article"} }],
  ["/posts/dragonfruit.html", { loader: () => import(/* webpackChunkName: "posts_dragonfruit.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/dragonfruit.html.js"), meta: {"date":1641772800000,"category":["火龙果","水果"],"tag":["红","大"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.12,"words":36},"title":"火龙果","icon":"pen-to-square","type":"article"} }],
  ["/posts/strawberry.html", { loader: () => import(/* webpackChunkName: "posts_strawberry.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/strawberry.html.js"), meta: {"date":1641859200000,"category":["水果","草莓"],"tag":["红","小"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.11,"words":34},"title":"草莓","icon":"pen-to-square","type":"article"} }],
  ["/posts/tomato.html", { loader: () => import(/* webpackChunkName: "posts_tomato.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/tomato.html.js"), meta: {"date":1641945600000,"category":["蔬菜"],"tag":["红","圆"],"sticky":true,"cover":"/assets/images/cover2.jpg","excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.13,"words":38},"title":"番茄","icon":"pen-to-square","type":"article"} }],
  ["/posts/apple/1.html", { loader: () => import(/* webpackChunkName: "posts_apple_1.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/apple/1.html.js"), meta: {"date":1640995200000,"category":["苹果"],"tag":["红","大","圆"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.11,"words":34},"title":"苹果 1","icon":"pen-to-square","type":"article"} }],
  ["/posts/apple/2.html", { loader: () => import(/* webpackChunkName: "posts_apple_2.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/apple/2.html.js"), meta: {"date":1641081600000,"category":["苹果"],"tag":["红","大","圆"],"excerpt":"\n<p>一个被星标了的苹果文章。</p>\n","readingTime":{"minutes":0.16,"words":48},"title":"苹果 2","icon":"pen-to-square","type":"article"} }],
  ["/posts/apple/3.html", { loader: () => import(/* webpackChunkName: "posts_apple_3.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/apple/3.html.js"), meta: {"date":1641168000000,"category":["苹果","水果"],"tag":["红","大","圆"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.12,"words":36},"title":"苹果 3","icon":"pen-to-square","type":"article"} }],
  ["/posts/apple/4.html", { loader: () => import(/* webpackChunkName: "posts_apple_4.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/apple/4.html.js"), meta: {"date":1641254400000,"category":["苹果","水果"],"tag":["红","大","圆"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.12,"words":36},"title":"苹果 4","icon":"pen-to-square","type":"article"} }],
  ["/posts/banana/1.html", { loader: () => import(/* webpackChunkName: "posts_banana_1.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/banana/1.html.js"), meta: {"date":1641340800000,"category":["香蕉","水果"],"tag":["黄","弯曲的","长"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.13,"words":38},"title":"香蕉 1","icon":"pen-to-square","type":"article"} }],
  ["/posts/banana/2.html", { loader: () => import(/* webpackChunkName: "posts_banana_2.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/banana/2.html.js"), meta: {"date":1641427200000,"category":["香蕉","水果"],"tag":["黄","弯曲的","长"],"excerpt":"\n<p>一个被数字 <code>10</code> 星标了的香蕉文章。</p>\n","readingTime":{"minutes":0.18,"words":55},"title":"香蕉 2","icon":"pen-to-square","type":"article"} }],
  ["/posts/banana/3.html", { loader: () => import(/* webpackChunkName: "posts_banana_3.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/banana/3.html.js"), meta: {"date":1641513600000,"category":["香蕉"],"tag":["黄","弯曲的","长"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.12,"words":36},"title":"香蕉 3","icon":"pen-to-square","type":"article"} }],
  ["/posts/banana/4.html", { loader: () => import(/* webpackChunkName: "posts_banana_4.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/banana/4.html.js"), meta: {"date":1641600000000,"category":["香蕉"],"tag":["黄","弯曲的","长"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.12,"words":36},"title":"香蕉 4","icon":"pen-to-square","type":"article"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/404.html.js"), meta: {"title":""} }],
  ["/posts/", { loader: () => import(/* webpackChunkName: "posts_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/index.html.js"), meta: {"title":"Posts"} }],
  ["/posts/apple/", { loader: () => import(/* webpackChunkName: "posts_apple_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/apple/index.html.js"), meta: {"title":"Apple"} }],
  ["/posts/banana/", { loader: () => import(/* webpackChunkName: "posts_banana_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/posts/banana/index.html.js"), meta: {"title":"Banana"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/category/index.html.js"), meta: {"title":"分类","index":false} }],
  ["/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/", { loader: () => import(/* webpackChunkName: "category_使用指南_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/category/使用指南/index.html.js"), meta: {"title":"使用指南 分类","index":false} }],
  ["/category/%E6%8C%87%E5%8D%97/", { loader: () => import(/* webpackChunkName: "category_指南_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/category/指南/index.html.js"), meta: {"title":"指南 分类","index":false} }],
  ["/category/%E6%A8%B1%E6%A1%83/", { loader: () => import(/* webpackChunkName: "category_樱桃_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/category/樱桃/index.html.js"), meta: {"title":"樱桃 分类","index":false} }],
  ["/category/%E7%81%AB%E9%BE%99%E6%9E%9C/", { loader: () => import(/* webpackChunkName: "category_火龙果_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/category/火龙果/index.html.js"), meta: {"title":"火龙果 分类","index":false} }],
  ["/category/%E6%B0%B4%E6%9E%9C/", { loader: () => import(/* webpackChunkName: "category_水果_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/category/水果/index.html.js"), meta: {"title":"水果 分类","index":false} }],
  ["/category/%E8%8D%89%E8%8E%93/", { loader: () => import(/* webpackChunkName: "category_草莓_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/category/草莓/index.html.js"), meta: {"title":"草莓 分类","index":false} }],
  ["/category/%E8%94%AC%E8%8F%9C/", { loader: () => import(/* webpackChunkName: "category_蔬菜_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/category/蔬菜/index.html.js"), meta: {"title":"蔬菜 分类","index":false} }],
  ["/category/%E8%8B%B9%E6%9E%9C/", { loader: () => import(/* webpackChunkName: "category_苹果_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/category/苹果/index.html.js"), meta: {"title":"苹果 分类","index":false} }],
  ["/category/%E9%A6%99%E8%95%89/", { loader: () => import(/* webpackChunkName: "category_香蕉_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/category/香蕉/index.html.js"), meta: {"title":"香蕉 分类","index":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/index.html.js"), meta: {"title":"标签","index":false} }],
  ["/tag/%E7%A6%81%E7%94%A8/", { loader: () => import(/* webpackChunkName: "tag_禁用_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/禁用/index.html.js"), meta: {"title":"标签: 禁用","index":false} }],
  ["/tag/%E5%8A%A0%E5%AF%86/", { loader: () => import(/* webpackChunkName: "tag_加密_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/加密/index.html.js"), meta: {"title":"标签: 加密","index":false} }],
  ["/tag/%E5%B8%83%E5%B1%80/", { loader: () => import(/* webpackChunkName: "tag_布局_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/布局/index.html.js"), meta: {"title":"标签: 布局","index":false} }],
  ["/tag/markdown/", { loader: () => import(/* webpackChunkName: "tag_markdown_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/markdown/index.html.js"), meta: {"title":"标签: Markdown","index":false} }],
  ["/tag/%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE/", { loader: () => import(/* webpackChunkName: "tag_页面配置_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/页面配置/index.html.js"), meta: {"title":"标签: 页面配置","index":false} }],
  ["/tag/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/", { loader: () => import(/* webpackChunkName: "tag_使用指南_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/使用指南/index.html.js"), meta: {"title":"标签: 使用指南","index":false} }],
  ["/tag/%E7%BA%A2/", { loader: () => import(/* webpackChunkName: "tag_红_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/红/index.html.js"), meta: {"title":"标签: 红","index":false} }],
  ["/tag/%E5%B0%8F/", { loader: () => import(/* webpackChunkName: "tag_小_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/小/index.html.js"), meta: {"title":"标签: 小","index":false} }],
  ["/tag/%E5%9C%86/", { loader: () => import(/* webpackChunkName: "tag_圆_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/圆/index.html.js"), meta: {"title":"标签: 圆","index":false} }],
  ["/tag/%E5%A4%A7/", { loader: () => import(/* webpackChunkName: "tag_大_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/大/index.html.js"), meta: {"title":"标签: 大","index":false} }],
  ["/tag/%E9%BB%84/", { loader: () => import(/* webpackChunkName: "tag_黄_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/黄/index.html.js"), meta: {"title":"标签: 黄","index":false} }],
  ["/tag/%E5%BC%AF%E6%9B%B2%E7%9A%84/", { loader: () => import(/* webpackChunkName: "tag_弯曲的_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/弯曲的/index.html.js"), meta: {"title":"标签: 弯曲的","index":false} }],
  ["/tag/%E9%95%BF/", { loader: () => import(/* webpackChunkName: "tag_长_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/tag/长/index.html.js"), meta: {"title":"标签: 长","index":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/article/index.html.js"), meta: {"title":"文章","index":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/star/index.html.js"), meta: {"title":"星标","index":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"D:/web-front-workspace/demostudio/src/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"title":"时间轴","index":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
